### PR TITLE
yarn upgrade heroku-cli-addons

### PR DESCRIPTION
**Pull request by ransombriggs**
@jdxcode @RasPhilCo could you review?

### CODE REVIEW

**Comment by ransombriggs** [comment]
@jdxcode @RasPhilCo broke the tests, will fix

**Review by jdx — APPROVED** [review]

**Comment by msakrejda** [comment]
@ransombriggs test seem to be broken in CI and I have not been able to track down what the issue is yet. Run locally to check it in the meantime.

Anything @heroku/dod-ux should know about in this dep bump, or just routine?

**Comment by ransombriggs** [comment]
@uhoh-itsmaciek will work on getting the test suite to pass, am surprised it failed since I had assumed it would not change anything in the resolver.

**Comment by ransombriggs** [comment]
@uhoh-itsmaciek I got the test suite passing by using yarn to install deps instead of npm.  This should not have any large implications for `heroku-pg` in that it does not change the resolving logic at all, was just trying to reduce dep duplication.

**Review by RasPhilCo — APPROVED** [review]
🏄

**Comment by ransombriggs** [comment]
@uhoh-itsmaciek could you review as well, want to make you are comfortable before I ship, I scanned the commits between versions and it looked alright to me, but can detail them if you want.

**Review by msakrejda — APPROVED** [review]
Ship it ❤️

**Pull request merged**
