### PR TITLE
Only allow upgrading follower databases

### PR DESCRIPTION
**Pull request by msakrejda**
The Shogun upgrade endpoint has a check for this, but we need to
resolve the URL before we call to Shogun, so check this ourselves.

/cc @mrpaulsmith

### CODE REVIEW

**Comment by fnando** [comment]
Needs review. cc @fnando @brettgoulder

**Review by kvlou — APPROVED** [review]
looks legit

**Review by keiko713 — APPROVED** [review]
support folks got confused, would be nice to ship asap 🌮

**Comment by kwlockwo** [comment]
With this change, we should fix our documentation: https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases#upgrading-with-pg-upgrade

> Unlike with other database upgrade methods, no new instance of your database is created

If it only works on a follower this isn't true.

**Comment by keiko713** [comment]
@kwlockwo can you please leave that comment as a Dev Center feedback? it's a good feedback and would like to see it fixed

**Pull request merged**
