### PR TITLE
Bump node to the version currently in use in the CLI

### PR DESCRIPTION
**Pull request by msakrejda**
This fails tests right now, but I wanted to

 1. Open a PR to bump the version to make it clear we're drifting from the CLI and should update
 2. Ideally come up with some way of not drifting in CI, so we test against the node version our customers use

I want to address this after fixing the [current failures in CI](https://circleci.com/gh/heroku/heroku-pg/699#tests/containers/0) (that I have not been able to reproduce in running the tests locally).

### CODE REVIEW

**Comment by fnando** [comment]
Maciek need to gets back to this. Soon. Eventually. Maybe.

**Comment by msakrejda** [comment]
Ok, fixed and ready for review. Upgrading nock fixed the broken tests but broke twenty-some others due to some unintended changes in their mocking API and [awful error messages](https://github.com/node-nock/nock/issues/1052). I updated the broken tests.

**Comment by mehtaphysical** [comment]
@uhoh-itsmaciek I fixed these tests in a different PR #180 :/

**Comment by msakrejda** [comment]
Oh, sorry about that @mehtaphysical. I started working on this before you opened the issue, I think, but then yak shaved into filing the nock bug I linked above, which slowed this down. Thanks anyway!

**Review by fnando — APPROVED** [review]
Looks good.

**Pull request merged**
